In [47]:
import numpy as np
from scipy.linalg import null_space

In [7]:
def create_bootstrap_matrix(n, contract_ranges):
    m = len(contract_ranges)
    A = np.zeros((m, n))
    for i, contract in enumerate(contract_ranges):
        start_col, end_col = contract
        num_cols = end_col - start_col
        weight = 1.0/num_cols
        for j in range(start_col, end_col):
            A[i, j] = weight
    return A

In [31]:
contracts = [
    (0, 3),
    (3, 5),
    (4, 6)
]
n = 6
A = create_bootstrap_matrix(n, contracts)
print('A')
print(A)
prices = np.array((10.0, 10.0, 10.0))
print('prices')
print(prices)
pinv = np.linalg.pinv(A)
print('pseudo-inverse')
print(pinv)
bootstrapped_prices = np.matmul(pinv, prices)
print('bootstrapped')
print(bootstrapped_prices)

A
[[0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
 [0.         0.         0.         0.5        0.5        0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]]
prices
[10. 10. 10.]
pseudo-inverse
[[ 1.00000000e+00 -3.13011650e-17  2.40646826e-16]
 [ 1.00000000e+00  4.27581865e-17 -3.28729678e-16]
 [ 1.00000000e+00 -1.14570215e-17  8.80828517e-17]
 [ 0.00000000e+00  1.33333333e+00 -6.66666667e-01]
 [ 0.00000000e+00  6.66666667e-01  6.66666667e-01]
 [ 0.00000000e+00 -6.66666667e-01  1.33333333e+00]]
bootstrapped
[10.         10.         10.          6.66666667 13.33333333  6.66666667]


In [32]:
svd = np.linalg.svd(A)
svd

(array([[ 0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.        , -0.70710678],
        [ 0.70710678,  0.        ,  0.70710678]]),
 array([0.8660254 , 0.57735027, 0.5       ]),
 array([[ 1.28197512e-16, -1.75121059e-16,  4.69235462e-17,
          4.08248290e-01,  8.16496581e-01,  4.08248290e-01],
        [ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 9.61481343e-17, -1.31340794e-16,  3.51926597e-17,
         -7.07106781e-01,  2.77555756e-16,  7.07106781e-01],
        [ 1.72546030e-01, -6.43950551e-01,  4.71404521e-01,
          3.33333333e-01, -3.33333333e-01,  3.33333333e-01],
        [ 6.43950551e-01, -4.71404521e-01, -1.72546030e-01,
         -3.33333333e-01,  3.33333333e-01, -3.33333333e-01],
        [ 4.71404521e-01,  1.72546030e-01, -6.43950551e-01,
          3.33333333e-01, -3.33333333e-01,  3.33333333e-01]]))

In [46]:
ns = linalg.null_space(A)
ns

array([[ 0.17254603,  0.64395055,  0.47140452],
       [-0.64395055, -0.47140452,  0.17254603],
       [ 0.47140452, -0.17254603, -0.64395055],
       [ 0.33333333, -0.33333333,  0.33333333],
       [-0.33333333,  0.33333333, -0.33333333],
       [ 0.33333333, -0.33333333,  0.33333333]])

In [49]:
target = np.array([10.0, 10.0, 10.0, 10.0, 10.0, 10.0])
print('target')
print(target)
error = target - bootstrapped_prices
print('error')
print(error)


target
[10. 10. 10. 10. 10. 10.]
error
[-1.77635684e-15  3.55271368e-15  0.00000000e+00  3.33333333e+00
 -3.33333333e+00  3.33333333e+00]


In [50]:
c = np.matmul(ns.T, error)
print(c)

[ 3.33333333 -3.33333333  3.33333333]


In [52]:
y = bootstrapped_prices + np.matmul(ns, c)
y

array([10., 10., 10., 10., 10., 10.])